# backend/app/llm/gemini_provider.py

import httpx
from fastapi import status

from app.core.errors import AppException
from app.llm.base import BaseLLMProvider, LLMMessage, LLMResponse


class GeminiLLMProvider(BaseLLMProvider):
    def __init__(
        self,
        api_key: str,
        model_name: str = "gemini-1.5-flash",
        base_url: str = "https://generativelanguage.googleapis.com/v1beta",
    ):
        self.api_key = api_key
        self.model_name = model_name.replace("models/", "")
        self.base_url = base_url.rstrip("/")

    async def generate_response(
        self, messages: list[LLMMessage], temperature: float = 0.1, max_tokens: int = 1500
    ) -> LLMResponse:
        system_instruction = None
        contents = []

        for m in messages:
            if m.role == "system":
                system_instruction = {"parts": [{"text": m.content}]}
            else:
                role = "user" if m.role == "user" else "model"
                contents.append({"role": role, "parts": [{"text": m.content}]})

        payload = {
            "contents": contents,
            "generationConfig": {"temperature": temperature, "maxOutputTokens": max_tokens},
        }
        if system_instruction:
            payload["systemInstruction"] = system_instruction

        url = f"{self.base_url}/models/{self.model_name}:generateContent?key={self.api_key}"

        async with httpx.AsyncClient(timeout=45.0) as client:
            resp = await client.post(url, json=payload)
            if resp.status_code != 200:
                raise AppException(
                    code="GEMINI_LLM_ERROR",
                    message=f"Gemini API returned error: {resp.text}",
                    status_code=status.HTTP_502_BAD_GATEWAY,
                )
            data = resp.json()
            candidates = data.get("candidates", [])
            if not candidates:
                content = "No response generated by Gemini."
            else:
                content = candidates[0]["content"]["parts"][0]["text"]

            usage = data.get("usageMetadata", {})
            return LLMResponse(content=content, model_name=self.model_name, usage=usage)
